#!/bin/bash
# ============================================================
# 박근필성장연구소 전체 사이트 무결성 체크 v3
# 모든 작업 전·후 반드시 실행
# ============================================================
OK=0; FAIL=0
check() {
  local label="$1" file="$2" pattern="$3" min="${4:-1}"
  local count=$(grep -c "$pattern" "$file" 2>/dev/null || echo 0)
  if [ "$count" -ge "$min" ]; then
    echo "✅ $label: ${count}건"
    OK=$((OK+1))
  else
    echo "❌ $label: ${count}건 (최소 ${min}건) ← 누락!"
    FAIL=$((FAIL+1))
  fi
}

echo "====== 박근필성장연구소 전체 사이트 무결성 체크 ======"

echo ""
echo "── author.html ─────────────────────────────────────"
check "트레바리" /mnt/project/author.html "trevari"
check "자립지원관" /mnt/project/author.html "자립지원관"
check "두피디아" /mnt/project/author.html "Doopedia"
check "계양중" /mnt/project/author.html "계양중"
check "부산시청강연" /mnt/project/author.html "1cA7WuT"
check "historyData" /mnt/project/author.html "historyData"
check "columnData" /mnt/project/author.html "columnData"
check "history-activities" /mnt/project/author.html "history-activities"
check "history-interviews" /mnt/project/author.html "history-interviews"
check "column-section-3" /mnt/project/author.html "column-section-3"
check "뉴스테이션인터뷰(7380)" /mnt/project/author.html "7380"
check "뉴스앤잡인터뷰(32467)" /mnt/project/author.html "32467"
check "한국강사신문인터뷰(197706)" /mnt/project/author.html "197706"
check "커리어온인터뷰(473344)" /mnt/project/author.html "473344"
check "미디어파인인터뷰(75486)" /mnt/project/author.html "75486"
check "대한민국교육인터뷰(390683)" /mnt/project/author.html "390683"
check "뉴스클레임인터뷰(3056718)" /mnt/project/author.html "3056718"
check "BookNews인터뷰" /mnt/project/author.html "booknews"
check "SLICE인터뷰" /mnt/project/author.html "myslice"
check "월간리더스인터뷰" /mnt/project/author.html "kleadersforum"
check "CEO저널인터뷰" /mnt/project/author.html "ceojhn"
check "한국인공지능신문" /mnt/project/author.html "k-ainews"
check "뉴스테이션칼럼(7442)" /mnt/project/author.html "7442"
check "한국강사신문칼럼(200825)" /mnt/project/author.html "200825"
check "학생과청소년(3736)" /mnt/project/author.html "3736"
check "출판교육문화뉴스" /mnt/project/author.html "editbiznews"
check "캐어유뉴스(9407)" /mnt/project/author.html "9407"
check "호남교육신문(252501)" /mnt/project/author.html "252501"
check "코스미안뉴스" /mnt/project/author.html "cosmiannews"
check "미디어파인칼럼(75653)" /mnt/project/author.html "75653"
check "이로운넷" /mnt/project/author.html "eroun.net"
check "아웃소싱타임즈" /mnt/project/author.html "outsourcing.co.kr"
check "PPSS" /mnt/project/author.html "ppss.kr"
check "뉴스후플러스" /mnt/project/author.html "newswhoplus"
check "이모작뉴스" /mnt/project/author.html "emozak"
check "독서신문" /mnt/project/author.html "readersnews"
check "커리어온칼럼(475494)" /mnt/project/author.html "475494"
check "키즈맘" /mnt/project/author.html "kizmom"
check "경인미래교육신문" /mnt/project/author.html "ki-edu"
check "더에듀" /mnt/project/author.html "te.co.kr"
check "경인열린신문" /mnt/project/author.html "kiyln"
check "교육플러스" /mnt/project/author.html "edpl.co.kr"
check "뉴스프리존" /mnt/project/author.html "newsfreezone"
check "대한민국교육칼럼(395878)" /mnt/project/author.html "395878"
check "뉴스클레임칼럼(3057134)" /mnt/project/author.html "3057134"
check "뉴스앤잡칼럼(32725)" /mnt/project/author.html "32725"
check "에듀진" /mnt/project/author.html "edujin"
check "데일리개원" /mnt/project/author.html "dailygaewon"
check "데일리벳(245197)" /mnt/project/author.html "245197"
check "한국독서교육신문" /mnt/project/author.html "readingnews"

echo ""
echo "── newsletter.html ─────────────────────────────────"
check "필레터1호" /mnt/project/newsletter.html "필레터 정규 1호"
check "필레터5호" /mnt/project/newsletter.html "필레터 정규 5호"
check "필레터10호" /mnt/project/newsletter.html "필레터 정규 10호"
check "필레터15호" /mnt/project/newsletter.html "필레터 정규 15호"
check "필레터16호" /mnt/project/newsletter.html "필레터 정규 16호"
check "필레터17호" /mnt/project/newsletter.html "필레터 정규 17호"
check "필레터18호" /mnt/project/newsletter.html "필레터 정규 18호"
check "필레터19호" /mnt/project/newsletter.html "필레터 정규 19호"
check "필레터20호" /mnt/project/newsletter.html "필레터 정규 20호"
check "newsletter-manifest" /mnt/project/newsletter.html "newsletterManifest"

echo ""
echo "── books.html ──────────────────────────────────────"
check "booksData(JS)" /mnt/project/books.html "booksData"
check "books-container" /mnt/project/books.html "books-container"
check "저서1(book1)" /mnt/project/books.html "book1.jpg"
check "저서2(book2)" /mnt/project/books.html "book2.jpg"
check "저서3(book3)" /mnt/project/books.html "book3.jpg"
check "저서4(book4)" /mnt/project/books.html "book4.jpg"
check "교보문고링크" /mnt/project/books.html "kyobobook" 4

echo ""
echo "── notice.html ─────────────────────────────────────"
check "noticeData(JS)" /mnt/project/notice.html "noticeData"
check "notice-container" /mnt/project/notice.html "notice-container"
check "카카오오픈채팅" /mnt/project/notice.html "open.kakao"
check "리브랜딩공지" /mnt/project/notice.html "rebranding"
check "QR코드공지" /mnt/project/notice.html "qrcode"

echo ""
echo "── vod.html ────────────────────────────────────────"
check "vodData(JS)" /mnt/project/vod.html "vodData"
check "vod-previews-container" /mnt/project/vod.html "vod-previews-container"
check "VOD1(driveId)" /mnt/project/vod.html "1ArTCtIaDa88o6DwPAlFoX_i4-5ogJAtN"
check "VOD2(driveId)" /mnt/project/vod.html "1llkmwsrP41J6vmqlMDn1tx5zW1-emJRo"
check "VOD3(driveId)" /mnt/project/vod.html "1EOlnwG6EaJMy3df1rnf1GHac_UNa4VNf"
check "VOD4(driveId)" /mnt/project/vod.html "1giWnt-McveS0qBT_NLq-IMQWNB3nVo0q"
check "VOD5(driveId)" /mnt/project/vod.html "1Q8UdyrTi0Lq1Eb7xOFYLOex7QKpmInqA"

echo ""
echo "── people-insight.html ─────────────────────────────"
check "peopleInsightData(JS)" /mnt/project/people-insight.html "peopleInsightData"
check "people-insight-container" /mnt/project/people-insight.html "people-insight-container"
check "유튜브플레이리스트" /mnt/project/people-insight.html "PL9gDAK_kh9BJl6wyOhDCvexqOSXNTKitH"

echo ""
echo "── philbook.html ───────────────────────────────────"
check "philbookData(manifest)" /mnt/project/philbook.html "philbookData"
check "필북4기" /mnt/project/philbook.html "필북 4기"
check "필북5기" /mnt/project/philbook.html "필북 5기"
check "필북6기" /mnt/project/philbook.html "필북 6기"
check "필북신청마감" /mnt/project/philbook.html "신청_마감"

echo ""
echo "── index.html ──────────────────────────────────────"
check "indexManifest(JS)" /mnt/project/index.html "indexManifest"
check "독저팅섹션" /mnt/project/index.html "id=\"dokjeoting\""
check "VOD섹션" /mnt/project/index.html "id=\"vod\""
check "필북섹션" /mnt/project/index.html "id=\"philbook\""
check "필레터섹션" /mnt/project/index.html "newsletter"
check "피플인사이트섹션" /mnt/project/index.html "people-insight"
check "저서섹션" /mnt/project/index.html "id=\"books\""
check "필북6기마감" /mnt/project/index.html "신청_마감"

echo ""
echo "── dokjeoting.html ─────────────────────────────────"
check "dokjeotingData(manifest)" /mnt/project/dokjeoting.html "dokjeotingData"
check "독저팅소개" /mnt/project/dokjeoting.html "독저팅"
check "독저팅신청" /mnt/project/dokjeoting.html "신청"

echo ""
echo "── phillife.html ───────────────────────────────────"
check "phillifeData(manifest)" /mnt/project/phillife.html "phillifeData"
check "필라이프소개" /mnt/project/phillife.html "필라이프"
check "필라이프코칭" /mnt/project/phillife.html "코칭"

echo ""
echo "======================================================"
echo "✅ 정상: ${OK}건 / ❌ 누락: ${FAIL}건"
if [ "$FAIL" -gt "0" ]; then
  echo "⚠️  누락 항목 발견! 즉시 복구 필요."
else
  echo "🎉 전체 이상 없음."
fi
echo "======================================================"
